---
title: "wea project"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)

# install.packages("gifski") #if not already installed

library(here)
library(tidyverse)
library(gganimate)
library(plotly)
library(htmlwidgets)
```

## Wea orj

https://www.metoffice.gov.uk/pub/data/weather/uk/climate/stationdata/sheffielddata.txt

https://tomstafford.github.io/wea/

```{r}

# -----------IMPORT DATA------------
source <- 'https://www.metoffice.gov.uk/pub/data/weather/uk/climate/stationdata/sheffielddata.txt'

# Read the contents of the file
file_content <- readLines(source)

# Replace all asterisks with an empty string
modified_content <- gsub("\\*", "", file_content)

modified_content <- gsub("\\#", "", modified_content)

modified_content <- gsub("Provisional", "", modified_content)

# Write the modified content back to the file
writeLines(modified_content, here("data","sanitised.txt"))

df <- read.table(here("data","sanitised.txt"), skip=7, fill=TRUE)

col_names <- c("year","month", "max_t", "min_t", "days", "rain", "sun")

colnames(df) <- col_names

# -----------TIDY DATA------------
cf <- df %>% 
  mutate(sun = parse_number(sun)) %>% # remove non-numeric data
  mutate(year=as.numeric(year), # change data type to numeric
         max_t=as.numeric(max_t),
         min_t=as.numeric(min_t),
         days=as.numeric(days),
         rain=as.numeric(rain))
write.csv(cf, here("data", "tidy_data.csv"))

```

PLOTS

```{r}
# ----------MAKE SOME PLOTS------------

p <- ggplot(cf, mapping=aes(x=month, y=max_t, group=year,
                            col=year))
p + geom_line(alpha=.1) + 
  scale_color_gradient(low='blue', high='red')

p

july <- cf %>% 
  filter(month == 7)

p2 <- ggplot(july, mapping=aes(x=year, y=max_t, 
                               col=max_t))
p2 + geom_point()


```

ANIMATED

```{r}

average <- cf %>% 
  group_by(year) %>% 
  summarise(avg_upper = mean(max_t), 
            avg_lower = mean(min_t))


# -------LET'S ANIMATE-----
p3 <- ggplot(average, mapping=aes(x=year, y=avg_upper,
                                  frame=year))
#p3 + geom_point() 

anim <- p3 + geom_point() + 
  transition_manual(year, cumulative = TRUE) +
  ggtitle('The year is: {frame + 1882}')

anim

anim_save(here("plots", "average_by_year.gif"), anim, renderer = gifski_renderer())
```

ROLL OVER

```{r}
# -------LET'S ROLL OVER------
p4 <- ggplot(cf, mapping=aes(x=month, y=max_t, 
                             group=year, col=year)) +
  geom_line()

ggplotly(p4)

saveWidget(ggplotly(p4), file=here('plots','interactive.html'))


```